version: '2'
services:
  taskservice-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'discovery.type=single-node'
